import { create } from 'zustand';

export type Message = {
  id: string;
  role: 'user' | 'model';
  content: string;
  isStreaming?: boolean;
};

export type FileNode = {
  id: string;
  name: string;
  type: 'file' | 'folder';
  content?: string;
  children?: FileNode[];
  isOpen?: boolean;
};

interface AgentState {
  messages: Message[];
  addMessage: (msg: Message) => void;
  updateMessage: (id: string, content: string, isStreaming?: boolean) => void;
  
  files: FileNode[];
  selectedFile: FileNode | null;
  setSelectedFile: (file: FileNode | null) => void;
  setFiles: (files: FileNode[]) => void;
}

const initialFiles: FileNode[] = [
  {
    id: '1', name: 'src', type: 'folder', isOpen: true, children: [
        { id: '1-1', name: 'App.tsx', type: 'file', content: '// Agent will write code here' },
        { id: '1-2', name: 'styles.css', type: 'file', content: '/* Styles will be added here */' },
    ]
  },
  { id: '2', name: 'package.json', type: 'file', content: '{\n  "name": "nathan-app",\n  "version": "1.0.0"\n}' },
  { id: '3', name: 'README.md', type: 'file', content: '# Welcome to your new project\nGenerated by Nathan-coder.' },
];

export const useAgentStore = create<AgentState>((set) => ({
  messages: [{
    id: 'welcome',
    role: 'model',
    content: 'Hello! I am Nathan-coder. What would you like to build today?'
  }],
  addMessage: (msg) => set((state) => ({ messages: [...state.messages, msg] })),
  updateMessage: (id, content, isStreaming) => set((state) => ({
    messages: state.messages.map(m => m.id === id ? { ...m, content, isStreaming: isStreaming !== undefined ? isStreaming : m.isStreaming } : m)
  })),
  
  files: initialFiles,
  selectedFile: null,
  setSelectedFile: (file) => set({ selectedFile: file }),
  setFiles: (files) => set({ files }),
}));
